apiVersion: v1
kind: ConfigMap

metadata:
  name: config
data:
  config.json: |2
          {
            "taskdb": "mysql+taskdb://root:acc!~1024@mysql.mysql.cluster.local:3306/taskdb",
            "projectdb": "mysql+projectdb://root:acc!~1024@mysql.mysql.cluster.local:3306/projectdb",
            "resultdb": "mysql+resultdb://root:acc!~1024@mysql.mysql.cluster.local:3306/resultdb",
            "message_queue": "redis://gitlab-redis.gitlab.cluster.local:6379/0",
            "webui": {
              "need-auth": false,
              "scheduler-rpc": "http://pyspider-scheduler:23333",
              "fetcher-rpc": "http://pyspider-fetcher:24444"
            }
          }

